[package]
name = "project1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
linfa = "0.6"  
linfa-clustering = "0.6"  
ndarray = "0.15" 
rand = "0.8" 
serde = "1.0.200"
